# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-25 19:07
from __future__ import unicode_literals

from django.db import migrations, models
import posts.validators


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20170625_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(validators=[posts.validators.content_validation]),
        ),
    ]
